compat: don't reinterpret_cast NULL
On FreeBSD, NULL is defined as nullptr_t. We get following error

error: reinterpret_cast from 'nullptr_t' to 'foo *' is not allowed

Signed-off-by: Yan, Zheng <zyan@redhat.com>